//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.4952
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unpacker.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unpacker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ...           ...         ..         .  .. .              
        ///   .MMMM...   MM888.MMNMN8MMOM8N  OMMMMOMMMMM.MMMMDDDNMMMZ. MMMMNM8MZ$Z?.   
        ///  . MMMMZ..  IMMMMO.$NMMNMMMMMMN..87MDDNDNMMM.NMDM8DDNMMMD..MMMMMMMDZNO$..  
        /// .  MMMMMM. MMMMMMO.MMNDMNMMMMMN. N8ODMOMMMMM.MMMNMMNN8M$D..MMMNMNMN$DD8..  
        /// . .MMMMMMMMMMMNNMO.MMMMOM~ .  .... IDDMD=.. .MMMNN$78NODM..NMNM. .NZN88.   
        ///  ..MMMMMMMMMMMMNN,.NMMMMMM. .. ... .MMMM+ ...MDMNMMMMMNZN..MMMM  .ND8O7.   
        /// .. MMMMMMMMMMMMMM8.MMMMMMDO88Z7 .. ?MMMM+ ...DDMMMMNNMMNN..MM [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string m2033 {
            get {
                return ResourceManager.GetString("m2033", resourceCulture);
            }
        }
    }
}
